### ISSUE TITLE
btrfs.go:103: constant 18446744073709551616 overflows C.__u64

### ISSUE THREAD

**Issue by nim-nim** [containerd/btrfs#15]
With: 
-   github.com/containerd/btrfs 72c0a3512e5703f4f03f392167117122b550b6e8
-   btrfs-progs-devel.x86_64 4.14.1-1.fc28                                                                         
-   golang-github-pkg-errors-devel.noarch 0.7.1-0.5.gita887431.fc27               
-   btrfs-progs.x86_64 4.14.1-1.fc28                                              
-   e2fsprogs-libs.x86_64 1.43.8-1.fc28 

                                          
       
Tests fail with:
```shell
 + go test -buildmode pie -compiler gc -ldflags ' -X github.com/containerd/btrfs/version.commit=72c0a3512e5703f4f03f392167117122b550b6e8 -X github.com/containerd/btrfs/version=0 -extldflags '\''-Wl,-z,relro  -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
 # github.com/containerd/btrfs
 ./btrfs.go:103: constant 18446744073709551616 overflows C.__u64
 ./btrfs.go:104: constant 18446744073709551616 overflows C.__u64
 ./btrfs.go:105: constant 18446744073709551616 overflows C.__u64
```

**Comment by carlwgeorge** [comment]
I'm seeing a similar error while trying to update the Fedora package for containerd, which vendors `github.com/containerd/btrfs` at cc52c4dea2ce11a44e6639e561bb5c2af9ada9e3.

```
# go build -ldflags "-X github.com/containerd/containerd/version.Package=github.com/containerd/containerd -X github.com/containerd/containerd/version.Version=v1.0.2 -X github.com/containerd/containerd/version.Revision=cfd04396dc68220d1cecbe686a6cc3aa5ce3667c" -o bin/containerd -a $IP/cmd/containerd
# github.com/containerd/containerd/vendor/github.com/containerd/btrfs
src/github.com/containerd/containerd/vendor/github.com/containerd/btrfs/btrfs.go:103: constant 18446744073709551616 overflows _Ctype_ulonglong
src/github.com/containerd/containerd/vendor/github.com/containerd/btrfs/btrfs.go:104: constant 18446744073709551616 overflows _Ctype_ulonglong
src/github.com/containerd/containerd/vendor/github.com/containerd/btrfs/btrfs.go:105: constant 18446744073709551616 overflows _Ctype_ulonglong
```

**Comment by nim-nim** [comment]
Yes my build is part of an attempt to update the whole Fedora Go baseline to more current versions, unbundling everything that can be to clearly identify failing code and making sure all Go packages are built with the flags defined by the Fedora golang maintainer

**Comment by stevvooe** [comment]
@nim-nim What are you asking here? That constant is defined in the build environment. https://github.com/containerd/btrfs/blob/master/btrfs.go#L103 is one example. This is assigning a C defined constant to a C-defined field, so something is wrong with the compiler environment that prevents this from working.

My guess is that the constant needs to be masked for the size of `max_objectid` for a given architecture. What arch is this on? (also, please provide go version and any other environment information).

Could you also try the following patch?

```diff
diff --git a/btrfs.go b/btrfs.go
index 1deab47..84acaae 100644
--- a/btrfs.go
+++ b/btrfs.go
@@ -100,7 +100,7 @@ func subvolMap(path string) (map[uint64]*Info, error) {
        args.key.min_type = C.BTRFS_ROOT_ITEM_KEY
        args.key.max_type = C.BTRFS_ROOT_BACKREF_KEY
        args.key.min_objectid = C.BTRFS_FS_TREE_OBJECTID
-       args.key.max_objectid = C.u64_BTRFS_LAST_FREE_OBJECTID
+       args.key.max_objectid = C.BTRFS_LAST_FREE_OBJECTID
        args.key.max_offset = C.negative_one
        args.key.max_transid = C.negative_one
```

**Comment by nim-nim** [comment]
@stevvooe I'm not asking anything, just pointing that the unit test fails with recent btrfs versions shipped by Fedora

The test is run with 1.9.4 on x86_64, about as standard and recent that can be without using pre-release parts or uncommon architectures.

I'll try the patch next

**Comment by stevvooe** [comment]
@nim-nim Looking at https://github.com/kdave/btrfs-progs/blob/v4.14.1/ctree.h, it doesn't seem like there were any changes in btrfs-progs that would affect this. What Go version are you using? Are there any patches?

I am sorry to ask more questions, but I have no way of reproducing this environment. If you could provide an easy way to demonstrate this, I can probably find a fix.

**Comment by carlwgeorge** [comment]
@stevvooe The environment is Fedora 28 (_btrfs-progs-devel.x86_64 4.14.1-1._**fc28**).  That hasn't been released yet, but if you create a Fedora 27 virtual machine or cloud server, you can use `dnf system-upgrade` to update it to the pre-release Fedora 28 repos.  I can help you get this set up if you like, is there a more interactive place we can chat about it?

As far as patches, yes there are a few in Fedora's golang.

https://src.fedoraproject.org/rpms/golang/blob/f28/f/golang.spec#_178-186
https://src.fedoraproject.org/rpms/golang/blob/f28/f/go1.5-zoneinfo_testing_only.patch
https://src.fedoraproject.org/rpms/golang/blob/f28/f/s390x-expose-IfInfomsg-X__ifi_pad.patch
https://src.fedoraproject.org/rpms/golang/blob/f28/f/golang-1.10-pkgconfig-fix.patch

Btrfs on the other hand appears to be vanilla upstream with no patches.

**Comment by nim-nim** [comment]
I should say that I hit the problem with golang 1.9.4
https://koji.fedoraproject.org/koji/buildinfo?buildID=1039638

I'm not brave enough to try go 1.10 yet

**Comment by stevvooe** [comment]
@carlwgeorge @nim-nim Any way I can do this in a container?

If not, you can reach out to me on docker community slack. I'm also on IRC, if that works, under the same name.

**Comment by carlwgeorge** [comment]
Yes, it is reproducible in a container.

commands:
```
docker pull fedora:rawhide
docker run -it --rm fedora:rawhide bash
dnf install golang git btrfs-progs-devel
go get github.com/containerd/btrfs
```

final output:
```
root/go/src/github.com/containerd/btrfs/btrfs.go:103: constant 18446744073709551616 overflows _Ctype_ulonglong
root/go/src/github.com/containerd/btrfs/btrfs.go:104: constant 18446744073709551616 overflows _Ctype_ulonglong
root/go/src/github.com/containerd/btrfs/btrfs.go:105: constant 18446744073709551616 overflows _Ctype_ulonglong
```

(Note that the `fedora:rawhide` image is currently Fedora 28, but in the near future it will be Fedora 29.)

Running `go test` in `/root/go/src/github.com/containerd/btrfs` produces the same error.  I can't reproduce the `overflows C.__u64` errror @nim-nim had, but the line numbers match.

**Comment by nim-nim** [comment]
@carlwgeorge you built with Go 1.10; me with Go 1.9, the error message is slightly different but that's probably just a difference in the way the two Go versions report the same problem.

I'll try to redo a build as soon as possible, right now I'm stuck on the update of some Go packages that come before in mass rebuild order.

**Comment by carlwgeorge** [comment]
I tried a few things in Fedora 27, and they all worked.

- golang-1.9.4-1.fc27 + btrfs-progs-devel-4.11.1-3.fc27
- golang-1.9.4-1.fc27 + btrfs-progs-devel-4.15.1-1.fc28
- golang-1.10-0.rc2.1.fc28 + btrfs-progs-devel-4.11.1-3.fc27

What else changed between Fedora 27 and Fedora 28 that could cause this issue you think?

**Comment by nim-nim** [comment]
Given the error concerns C types, I'd tend to suspect glibc
Fedora 28 will include a huge glibc and gcc update

And it's not as if a mock build root contained a lot of things

**Comment by carlwgeorge** [comment]
Yup, looks to be gcc 8.  @stevvooe, here is your minimal reproducer.

```
docker run -it --rm fedora:27 bash
dnf install golang git btrfs-progs-devel
dnf --releasever=28 update gcc
go get github.com/containerd/btrfs
```

This gives you golang 1.9.4, btrfs-progs-devel 4.11.1, and gcc 8.0.1, and results in this output.

```
# github.com/containerd/btrfs
root/go/src/github.com/containerd/btrfs/btrfs.go:103: constant 18446744073709551616 overflows C.__u64
root/go/src/github.com/containerd/btrfs/btrfs.go:104: constant 18446744073709551616 overflows C.__u64
root/go/src/github.com/containerd/btrfs/btrfs.go:105: constant 18446744073709551616 overflows C.__u64
```

**Comment by stevvooe** [comment]
@carlwgeorge I got that far! :)

I am able to fix the one on line 103, but the others I don't have a fix for yet.

**Comment by stevvooe** [comment]
@nim-nim @carlwgeorge Could you give the below patch a try?

```diff
diff --git a/btrfs.go b/btrfs.go
index 1deab47..efdf528 100644
--- a/btrfs.go
+++ b/btrfs.go
@@ -7,10 +7,6 @@ import "sort"
 #include <btrfs/ioctl.h>
 #include "btrfs.h"
 
-// Required because Go has struct casting rules for negative numbers
-const __u64 u64_BTRFS_LAST_FREE_OBJECTID = (__u64)BTRFS_LAST_FREE_OBJECTID;
-const __u64 negative_one = (__u64)-1;
-
 static char* get_name_btrfs_ioctl_vol_args_v2(struct btrfs_ioctl_vol_args_v2* btrfs_struct) {
        return btrfs_struct->name;
 }
@@ -100,9 +96,9 @@ func subvolMap(path string) (map[uint64]*Info, error) {
        args.key.min_type = C.BTRFS_ROOT_ITEM_KEY
        args.key.max_type = C.BTRFS_ROOT_BACKREF_KEY
        args.key.min_objectid = C.BTRFS_FS_TREE_OBJECTID
-       args.key.max_objectid = C.u64_BTRFS_LAST_FREE_OBJECTID
-       args.key.max_offset = C.negative_one
-       args.key.max_transid = C.negative_one
+       args.key.max_objectid = C.BTRFS_LAST_FREE_OBJECTID
+       args.key.max_offset = ^C.__u64(0)
+       args.key.max_transid = ^C.__u64(0)
 
        subvolsByID := make(map[uint64]*Info)
```

**Comment by carlwgeorge** [comment]
That works for me to compile in both the minimal reproducer and to compile containerd with the vendored containerd/btrfs.

**Comment by stevvooe** [comment]
@carlwgeorge @nim-nim Ok, we'll go forward with #16.

**Comment by carlwgeorge** [comment]
Thanks @stevvooe!  Do you think this fix will be vendored into a containerd release soon?  Or should I go ahead and build containerd-1.0.2 for Fedora with the patch?

**Comment by stevvooe** [comment]
We can slate it for 1.0.3. Could you make an issue or a PR? If not, I'll try to take care of this afternoon.

**Comment by stevvooe** [comment]
@nim-nim @carlwgeorge I just wanted to thank you both for being responsive and helping get a fix here!
