### ISSUE TITLE
Copyright is missing

### ISSUE THREAD

**Issue by elboulangero** [containerd/btrfs#18]
Dear containerd authors,

I would like to package this library for Debian, however I couldn't find a copyright anywhere. This should be mentioned in the `LICENSE` file as well, right now the copyright line there is just a template.

https://github.com/containerd/btrfs/blob/9874fdfff052afdf879a315799ab38609d85753f/LICENSE#L189

Thanks

**Comment by stevvooe** [comment]
@elboulangero Thank you! It should read "The containerd Authors". I'll update this immediately.
