### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by gliptak** [containerd/btrfs#2]
Please correct:

https://travis-ci.org/stevvooe/go-btrfs/jobs/184599630
```
# github.com/stevvooe/go-btrfs
In file included from ./btrfs.go:10:0:
/usr/include/btrfs/btrfs-list.h:33:17: error: field 'rb_node' has incomplete type
  struct rb_node rb_node;
                 ^
/usr/include/btrfs/btrfs-list.h:34:17: error: field 'sort_node' has incomplete type
  struct rb_node sort_node;
                 ^
make: *** [test] Error 2
```
I'm also seeing this when trying to build ```docker/containerd```:

https://travis-ci.org/gliptak/containerd/jobs/185337854

Thanks

**Comment by samuelkarp** [comment]
I'm running into this problem as well when trying to run `make test` for containerd.  I suspect that I have a different version of the btrfs headers installed than what is expected by go-btrfs, or that I am missing some other dependency.

My environment right now is Ubuntu 14.04, Go 1.7.4, and [btrfs-tools 3.12-1ubuntu0.1](https://launchpad.net/ubuntu/+source/btrfs-tools/3.12-1ubuntu0.1).

**Comment by gliptak** [comment]
My build was also against `Ubuntu 14.04`

**Comment by samuelkarp** [comment]
Switching to Ubuntu 16.04 and using [btrfs-tools 4.4-1](https://launchpad.net/ubuntu/+source/btrfs-tools/4.4-1) gets this to work without modification.  I was also able to get go-btrfs to compile against 3.12-1ubuntu0.1 by making a few modifications, including removing `ruuid`.  @stevvooe, let me know if you want those changes as a pull request to enable it to build against old versions of btrfs.

**Comment by stevvooe** [comment]
@samuelkarp @gliptak The right fix here is to remove the call to [btrfs_getsubvol](https://github.com/stevvooe/go-btrfs/blob/master/btrfs.go#L82) and use `SubvolList` (or refactor it to do use something common underneath). No need to call into the btrfs C code and we can avoid licensing issues that arise.

**Comment by stevvooe** [comment]
@gliptak @samuelkarp Can you confirm the fix addressed the build issue?

**Comment by gliptak** [comment]
https://travis-ci.org/gliptak/containerd/jobs/189720420 Failures seem to be related:

```
--- FAIL: TestBtrfs (0.00s)

	btrfs_test.go:18: mkdir /tmp/snapshots/TestBtrfsPrepare-453949839: no such file or directory

mount: only root can do that

--- FAIL: TestSnapshotManagerBasic (0.00s)

	manager_test.go:49: [mount -t overlay none /tmp/test-layman-942281634/preparing -o upperdir=/tmp/test-layman-942281634/root/diff-848216217,workdir=/tmp/test-layman-942281634/root/work-103226660,lowerdir=/tmp/test-layman-942281634/root/empty]

	manager_test.go:53: exit status 1

--- FAIL: TestSnapshotNaiveBasic (0.00s)

	naive_test.go:20: /tmp/test-layman-577498163

	naive_test.go:61: copying of parent failed: chown /tmp/test-layman-577498163/root/active-426721270/data: operation not permitted

FAIL
```

**Comment by stevvooe** [comment]
@gliptak That looks completely unrelated. The error message says "mount: only root can do that".

I'm closing this one, as the compilation error is addressed.
