### ISSUE TITLE
won't compile against btrfs progs 4.10

### ISSUE THREAD

**Issue by TomasTomecek** [containerd/btrfs#8]
This is coming from containerd.

```
🐳 bin/ctr
🐳 bin/containerd
# github.com/containerd/containerd/vendor/github.com/stevvooe/go-btrfs
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libbtrfs.so: undefined reference to `__error'
collect2: error: ld returned 1 exit status
make: *** [Makefile:137: bin/containerd] Error 2
```

My btrfs-progs is coming from my distribution:

```
btrfs-progs-devel-4.10.1-1.fc27.x86_64
```

Here's the precise soname:

```
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libbtrfs.so -> libbtrfs.so.0.1
```

**Comment by stevvooe** [comment]
Hopefully, #7 should address this.

Technically, isn't this a break on the btrfs-progs-devel package side? This should probably be reported upstream.

**Comment by stevvooe** [comment]
@TomasTomecek Is this still a problem? I think you need a newer version of btrfs-progs. I think I have 4.12 locally, but I haven't tried 4.11.

**Comment by TomasTomecek** [comment]
We can close. I'll reopen if I run into this again.
